name: CI
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - 'docs/**'
      - '*.md'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.12.1.0"]
        ghc: ["9.2", "9.4" , "9.6"]
    runs-on: ${{ matrix.os }}
    env:
      CONFIG: "--enable-tests"
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: sudo apt-get update && sudo apt-get install --assume-yes libsdl2-dev libglew-dev
      - run: cabal update
      - run: cabal freeze $CONFIG
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-
      - run: cabal build $CONFIG
      - run: cabal test $CONFIG
      - run: cabal haddock $CONFIG
      - run: cabal sdist
